startproject/apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
import views

urlpatterns = [
    url(r'^change-password/', auth_views.password_change, {
        'template_name': 'registration/password_change.html',
        'post_change_redirect': '/'}, name="password-change"),
    url(r'^login/', views.LoginView.as_view(), name="login"),
    url(r'^logout/', auth_views.logout, {'next_page': '/accounts/login/'}, name="logout"),
    url(r'^register/', views.RegisterView.as_view(), name="register"),
    url(r'^$', views.ProfileUpdateView.as_view(), name="profile"),
]

startproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap, index as sitemap_index

from sitemaps import sitemaps

handler500 = 'core.views.handler500'

# Urls for Grappelli will cause this settings to fail,
# so Debug Toolbar should go first.

if settings.DEBUG:
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
else:
    urlpatterns = []

urlpatterns += [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^sitemap\.xml$', sitemap_index, {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemap,
        {'sitemaps': sitemaps, 'template_name': 'sitemaps/sitemap.xml'}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
]

templates/base.html
{% load i18n staticfiles %}{% get_current_language as LANG %}<!DOCTYPE html>
<html lang="{{ LANG }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title|default_if_none:"Double Django" }}</title>
    {% if DEBUG %}<link href="{% static 'dist/style.css' %}" rel="stylesheet">
    {% else %}<link href="{% static 'dist/style.min.css' %}" rel="stylesheet">{% endif %}
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% if messages %}{% for msg in messages %}<div class="alert alert-{{ msg.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="{% trans "close"|capfirst %}"><span aria-hidden="true">&times;</span></button>
      {{ msg.message }}
    </div>{% endfor %}{% endif %}
    {% include 'navigation.html' %}
    <div class="container">{% block content %}{% endblock %}</div>
    <footer class="container">
      <hr><p>{% trans "copyrights"|capfirst %} &copy;2015 Krastaman Rastamarian</p>
    </footer>
    <script src="{% static 'lib/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'lib/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/navigation.html
{% load i18n %}<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navigation" aria-expanded="false">
        <span class="sr-only">{% trans "toggle navigation"|capfirst %}</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Project Template</a>
    </div>
    <div class="collapse navbar-collapse" id="main-navigation">
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_anonymous %}<li><a href="{% url 'accounts:login' %}">{% trans "login"|capfirst %}</a></li>
        {% else %}<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.get_full_name }}<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'accounts:profile' %}">{% trans "update profile"|title %}</a></li>
            <li><a href="{% url 'accounts:logout' %}">{% trans "logout"|title %}</a></li>
          </ul>
        </li>
        <li>
          <img src="{{ user.profile.avatar }}" width="36" height="36">
        </li>{% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>